name: "enel_gold"
version: "1.0.0"
profile: "enel_trino"
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  enel_gold:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    dimensions:
      +materialized: table
      +schema: gold
    marts:
      +materialized: incremental
      +schema: gold
      +incremental_strategy: merge

seeds:
  enel_gold:
    +schema: gold
