FROM apache/airflow:2.9.3-python3.12

WORKDIR /opt/airflow

COPY pyproject.toml README.md /opt/airflow/
COPY src/ /opt/airflow/src/
RUN pip install --no-cache-dir ".[platform]"
COPY airflow/dags/ /opt/airflow/dags/
