"""Fine-tune a lightweight embedding model on CPU and export it to ONNX.

The input is ``data/rag/training_triplets.jsonl`` generated by
``scripts/rag_prepare_training_data.py``.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

# Configura logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _load_training_deps():
    try:
        from sentence_transformers import InputExample, SentenceTransformer, losses
        from torch.utils.data import DataLoader
    except ImportError as exc:
        raise RuntimeError(
            "Instale as dependências de treino: "
            "pip install sentence-transformers torch optimum[onnxruntime]"
        ) from exc
    return InputExample, SentenceTransformer, losses, DataLoader


def _fallback_examples(input_example_cls: type) -> list[Any]:
    return [
        input_example_cls(
            texts=["O que é ACF?", "ACF é Alta Complexidade", "O medidor digital é bom"],
            label=1.0,
        ),
        input_example_cls(
            texts=["Medidor digital", "Tipos de medidor em SP", "ACF e ASF"],
            label=1.0,
        ),
    ]


def load_triplets(path: Path, input_example_cls: type) -> list[Any]:
    examples: list[Any] = []
    if not path.exists():
        logger.warning(f"Arquivo não encontrado: {path}. Usando dummy data para testes.")
        return _fallback_examples(input_example_cls)

    with open(path, encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            if not line.strip():
                continue
            try:
                data = json.loads(line)
            except json.JSONDecodeError as exc:
                logger.warning("JSON inválido em %s:%d: %s", path, line_number, exc)
                continue
            try:
                examples.append(
                    input_example_cls(
                        texts=[data["query"], data["positive"], data["negative"]]
                    )
                )
            except KeyError as exc:
                logger.warning("Triplet incompleto em %s:%d: %s", path, line_number, exc)
    return examples


def main() -> None:
    input_example_cls, sentence_transformer_cls, losses_module, data_loader_cls = (
        _load_training_deps()
    )
    base_dir = Path(__file__).resolve().parent.parent
    triplets_path = base_dir / "data/rag/training_triplets.jsonl"
    model_output_dir = base_dir / "data/rag/models/enel-minilm-onnx"

    logger.info("Carregando modelo base...")
    model_name = "sentence-transformers/all-MiniLM-L6-v2"
    model = sentence_transformer_cls(model_name)

    logger.info("Carregando dataset...")
    train_examples = load_triplets(triplets_path, input_example_cls)

    if not train_examples:
        logger.info("Sem dados de treino, gerando dummy para exportação ONNX...")
        train_examples = _fallback_examples(input_example_cls)

    train_dataloader = data_loader_cls(train_examples, shuffle=True, batch_size=2)
    train_loss = losses_module.MultipleNegativesRankingLoss(model=model)

    logger.info("Iniciando fine-tuning na CPU...")
    # Treino curto para CPU (epochs baixas)
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        epochs=1,
        warmup_steps=10,
        show_progress_bar=True,
    )

    logger.info("Treinamento concluído. Exportando para ONNX...")
    # Salvamos os pesos PyTorch temporariamente
    temp_dir = base_dir / "data/rag/models/temp_pytorch"
    model.save(str(temp_dir))

    # Exportar para ONNX usando Optimum
    try:
        from optimum.onnxruntime import ORTModelForFeatureExtraction
        from transformers import AutoTokenizer

        logger.info("Convertendo para formato ONNX O4 (Otimizado para CPU)...")
        ort_model = ORTModelForFeatureExtraction.from_pretrained(str(temp_dir), export=True)
        tokenizer = AutoTokenizer.from_pretrained(str(temp_dir))

        model_output_dir.mkdir(parents=True, exist_ok=True)
        ort_model.save_pretrained(str(model_output_dir))
        tokenizer.save_pretrained(str(model_output_dir))
        logger.info("Modelo ONNX salvo em: %s", model_output_dir)

    except ImportError:
        logger.error("Optimum não instalado. Exportação ONNX pulada.")
        logger.info("Modelo PyTorch salvo em: %s", temp_dir)


if __name__ == "__main__":
    main()
