"""Fine-tune a lightweight embedding model on CPU and export it to ONNX.

The input is ``data/rag/training_triplets.jsonl`` generated by
``scripts/rag_prepare_training_data.py``.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

# Configura logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _load_training_deps():
    try:
        from sentence_transformers import InputExample, SentenceTransformer, losses
        from torch.utils.data import DataLoader
    except ImportError as exc:
        raise RuntimeError(
            "Instale as dependências de treino: "
            "pip install sentence-transformers torch optimum[onnxruntime]"
        ) from exc
    return InputExample, SentenceTransformer, losses, DataLoader


def _fallback_examples(input_example_cls: type) -> list[Any]:
    return [
        input_example_cls(
            texts=["O que é ACF?", "ACF é Alta Complexidade", "O medidor digital é bom"],
            label=1.0,
        ),
        input_example_cls(
            texts=["Medidor digital", "Tipos de medidor em SP", "ACF e ASF"],
            label=1.0,
        ),
    ]


def load_triplets(path: Path, input_example_cls: type) -> list[Any]:
    examples: list[Any] = []
    if not path.exists():
        logger.warning(f"Arquivo não encontrado: {path}. Usando dummy data para testes.")
        return _fallback_examples(input_example_cls)

    with open(path, encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            if not line.strip():
                continue
            try:
                data = json.loads(line)
            except json.JSONDecodeError as exc:
                logger.warning("JSON inválido em %s:%d: %s", path, line_number, exc)
                continue
            try:
                examples.append(
                    input_example_cls(
                        texts=[data["query"], data["positive"], data["negative"]]
                    )
                )
            except KeyError as exc:
                logger.warning("Triplet incompleto em %s:%d: %s", path, line_number, exc)
    return examples


def export_feature_extractor_to_onnx(model: Any, output_dir: Path) -> None:
    """Export the underlying transformer encoder to ONNX for CPU inference."""
    import torch

    transformer = model[0]
    tokenizer = model.tokenizer
    auto_model = transformer.auto_model
    auto_model.eval()
    auto_model.to("cpu")

    output_dir.mkdir(parents=True, exist_ok=True)
    tokenizer.save_pretrained(str(output_dir))
    auto_model.config.save_pretrained(str(output_dir))

    encoded = tokenizer(
        ["Exemplo de texto para exportação ONNX."],
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt",
    )
    input_names = ["input_ids", "attention_mask"]
    inputs = (encoded["input_ids"], encoded["attention_mask"])
    if "token_type_ids" in encoded:
        input_names.append("token_type_ids")
        inputs = (*inputs, encoded["token_type_ids"])

    class EmbeddingWrapper(torch.nn.Module):
        def __init__(self, wrapped_model: torch.nn.Module) -> None:
            super().__init__()
            self.wrapped_model = wrapped_model

        def forward(
            self,
            input_ids: torch.Tensor,
            attention_mask: torch.Tensor,
            *args: torch.Tensor,
        ) -> tuple[torch.Tensor, torch.Tensor]:
            token_type_ids = args[0] if args else None
            outputs = self.wrapped_model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                token_type_ids=token_type_ids,
                return_dict=True,
            )
            token_embeddings = outputs.last_hidden_state
            mask = (
                attention_mask.unsqueeze(-1)
                .expand(token_embeddings.size())
                .to(token_embeddings.dtype)
            )
            sentence_embedding = torch.sum(token_embeddings * mask, dim=1)
            sentence_embedding = sentence_embedding / torch.clamp(mask.sum(dim=1), min=1e-9)
            sentence_embedding = torch.nn.functional.normalize(sentence_embedding, p=2, dim=1)
            return sentence_embedding, token_embeddings

    dynamic_axes = {
        name: {0: "batch_size", 1: "sequence_length"} for name in input_names
    }
    dynamic_axes["sentence_embedding"] = {0: "batch_size"}
    dynamic_axes["last_hidden_state"] = {0: "batch_size", 1: "sequence_length"}

    wrapper = EmbeddingWrapper(auto_model).eval()
    with torch.no_grad():
        torch.onnx.export(
            wrapper,
            inputs,
            output_dir / "model.onnx",
            input_names=input_names,
            output_names=["sentence_embedding", "last_hidden_state"],
            dynamic_axes=dynamic_axes,
            dynamo=False,
            opset_version=18,
        )


def main() -> None:
    input_example_cls, sentence_transformer_cls, losses_module, data_loader_cls = (
        _load_training_deps()
    )
    base_dir = Path(__file__).resolve().parent.parent
    triplets_path = base_dir / "data/rag/training_triplets.jsonl"
    model_output_dir = base_dir / "data/rag/models/enel-minilm-onnx"

    logger.info("Carregando modelo base...")
    model_name = "sentence-transformers/all-MiniLM-L6-v2"
    model = sentence_transformer_cls(model_name)

    logger.info("Carregando dataset...")
    train_examples = load_triplets(triplets_path, input_example_cls)

    if not train_examples:
        logger.info("Sem dados de treino, gerando dummy para exportação ONNX...")
        train_examples = _fallback_examples(input_example_cls)

    train_dataloader = data_loader_cls(train_examples, shuffle=True, batch_size=2)
    train_loss = losses_module.MultipleNegativesRankingLoss(model=model)

    logger.info("Iniciando fine-tuning na CPU...")
    # Treino curto para CPU (epochs baixas)
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        epochs=1,
        warmup_steps=10,
        show_progress_bar=True,
    )

    logger.info("Treinamento concluído. Exportando para ONNX...")
    # Salvamos os pesos PyTorch temporariamente
    temp_dir = base_dir / "data/rag/models/temp_pytorch"
    model.save(str(temp_dir))

    # Exportar para ONNX sem depender de APIs internas do Optimum/PyTorch.
    try:
        logger.info("Convertendo encoder para ONNX para inferência em CPU...")
        export_feature_extractor_to_onnx(model, model_output_dir)
        logger.info("Modelo ONNX salvo em: %s", model_output_dir)

    except Exception:
        logger.exception("Falha ao exportar ONNX. Mantendo modelo PyTorch salvo.")
        logger.info("Modelo PyTorch salvo em: %s", temp_dir)


if __name__ == "__main__":
    main()
