CREATE TABLE IF NOT EXISTS nessie.silver.notas_operacionais (
    cod_nota BIGINT,
    cod_uc BIGINT,
    cod_instalacao BIGINT,
    cod_distribuidora INT,
    cod_ut INT,
    cod_co INT,
    cod_base INT,
    cod_lote INT,
    tipo_servico STRING,
    flag_impacto_faturamento BOOLEAN,
    area_classificada_risco BOOLEAN,
    historico_incidentes_12m INT,
    tipo_instalacao STRING,
    horario_agendado STRING,
    flag_risco_manual BOOLEAN,
    data_criacao DATE,
    data_prevista DATE,
    data_execucao DATE,
    data_alteracao TIMESTAMP,
    status STRING,
    cod_colaborador INT,
    latitude DOUBLE,
    longitude DOUBLE,
    classificacao_acf_asf STRING,
    dias_atraso INT,
    status_atraso STRING,
    flag_risco BOOLEAN,
    _run_id STRING,
    _processed_at TIMESTAMP,
    _source_run_id STRING,
    _valid_from TIMESTAMP,
    _valid_to TIMESTAMP,
    _is_current BOOLEAN
)
USING iceberg
PARTITIONED BY (months(data_criacao));
